from __future__ import annotations

from models import CaseBible, PlotPlan, PlotStep


class PlotPlanner:
    def build_plan(self, case_bible: CaseBible) -> PlotPlan:
        investigator = "Detective Lena Marlowe"
        victim = case_bible.victim.name

        steps = [
            PlotStep(
                1,
                "setup",
                "discovery",
                "The Locked Estate",
                f"{investigator} arrives after the body of {victim} is found and orders the snowbound estate sealed.",
                "Map room",
                [investigator, victim, "Evelyn Cross", "Miles Dorian", "Nora Bell", "Julian Pike"],
                [],
                ["The suspects cannot leave the estate."],
                "9:20 PM",
            ),
            PlotStep(
                2,
                "setup",
                "survey",
                "Initial Scene Sweep",
                "The detective notices the unusual puncture wound and the disturbed display case before ordering toxicology.",
                "Map room",
                [investigator],
                ["E3", "E4"],
                ["The death may not be a natural collapse."],
                "9:30 PM",
            ),
            PlotStep(
                3,
                "setup",
                "interview",
                "Host Under Pressure",
                "Evelyn admits the victim planned to make a damaging announcement, exposing a circle of motives.",
                "West salon",
                [investigator, "Evelyn Cross"],
                [],
                ["The victim intended to accuse someone publicly that night."],
                "9:45 PM",
            ),
            PlotStep(
                4,
                "investigation",
                "evidence",
                "Tea Service Suspicion",
                "Nora's fingerprints on the cracked teacup make her the first apparent suspect.",
                "Lecture antechamber",
                [investigator, "Nora Bell"],
                ["E1"],
                ["Nora handled the victim's last drink."],
                "10:00 PM",
            ),
            PlotStep(
                5,
                "investigation",
                "alibi_check",
                "Archive Alibi Verification",
                "A catalog terminal log confirms Nora worked in the archive earlier than claimed but left before the murder window closed.",
                "Archive room",
                [investigator, "Nora Bell"],
                [],
                ["Nora's alibi is partial and requires more scrutiny."],
                "10:20 PM",
            ),
            PlotStep(
                6,
                "investigation",
                "interview",
                "The Author's Resentment",
                "Miles reveals the victim threatened to expose his plagiarism, strengthening motive but not method.",
                "Observatory",
                [investigator, "Miles Dorian"],
                ["E6"],
                ["Miles had reason to hate the victim."],
                "10:35 PM",
            ),
            PlotStep(
                7,
                "investigation",
                "alibi_check",
                "Observatory Alibi Verification",
                "A voice recorder timeline shows Miles stopped dictating before the critical minutes, weakening but not collapsing his alibi.",
                "Observatory",
                [investigator, "Miles Dorian"],
                ["E6"],
                ["Miles cannot account for every minute around the murder."],
                "10:50 PM",
            ),
            PlotStep(
                8,
                "investigation",
                "red_herring",
                "Financial Secrets in the Ashes",
                "The burned ledger scrap suggests Evelyn hid embezzlement, creating a powerful but misleading murder theory.",
                "West salon",
                [investigator, "Evelyn Cross"],
                ["E5"],
                ["Evelyn has a secret unrelated to the killing."],
                "11:05 PM",
            ),
            PlotStep(
                9,
                "investigation",
                "forensics",
                "Poison by Puncture",
                "Toxicology rules out poisoned tea and proves the victim was attacked with a digitalis-coated object.",
                "Improvised lab",
                [investigator],
                ["E3"],
                ["The tea-cup theory is false."],
                "11:25 PM",
            ),
            PlotStep(
                10,
                "investigation",
                "evidence",
                "The Missing Minutes",
                "Security logs reveal a manual deletion in the east corridor footage during the murder window.",
                "Security office",
                [investigator, "Julian Pike"],
                ["E2"],
                ["Someone with security access manipulated the cameras."],
                "11:40 PM",
            ),
            PlotStep(
                11,
                "midpoint",
                "interference",
                "A Witness Is Silenced",
                "Before Nora can explain a message she overheard, someone ransacks her desk and removes a note, signaling active interference.",
                "Archive room",
                [investigator, "Nora Bell"],
                [],
                ["The killer is still shaping the investigation."],
                "11:55 PM",
            ),
            PlotStep(
                12,
                "investigation",
                "evidence",
                "Message to the Map Room",
                "A recovered phone extract shows the victim was lured to the map room by a message from Julian's device.",
                "Guest wing",
                [investigator, "Julian Pike"],
                ["E8"],
                ["Julian contacted the victim just before the murder."],
                "12:10 AM",
            ),
            PlotStep(
                13,
                "investigation",
                "evidence",
                "Boot Prints Through the Basement",
                "Wet boot prints trace a path from the generator control panel toward the east stair, aligning with a staged outage.",
                "Basement corridor",
                [investigator, "Julian Pike"],
                ["E7", "E9"],
                ["The generator fault may have been manufactured."],
                "12:25 AM",
            ),
            PlotStep(
                14,
                "reversal",
                "analysis",
                "Red Herring Cleared",
                "The detective reconstructs the tea timeline and clears Nora, while Evelyn's fraud is split off as a separate offense.",
                "Drawing room",
                [investigator, "Nora Bell", "Evelyn Cross"],
                ["E1", "E3", "E5"],
                ["The real killer relied on the confusion created by side scandals."],
                "12:45 AM",
            ),
            PlotStep(
                15,
                "reversal",
                "analysis",
                "Means, Motive, Opportunity Aligned",
                "Julian alone had security access, a reason to stop the victim's revelation, and a route hidden by the outage.",
                "Drawing room",
                [investigator, "Julian Pike"],
                ["E2", "E7", "E8", "E9"],
                ["The evidence chain now centers on Julian."],
                "1:00 AM",
            ),
            PlotStep(
                16,
                "climax",
                "confrontation",
                "Confrontation in the Map Room",
                "The detective recreates the murder and confronts Julian with the deleted footage, the message extract, the toxin trace, and the staged outage.",
                "Map room",
                [investigator, "Julian Pike", "Evelyn Cross", "Miles Dorian", "Nora Bell"],
                ["E2", "E3", "E8", "E9"],
                ["Julian's basement alibi collapses under the evidence."],
                "1:20 AM",
            ),
            PlotStep(
                17,
                "resolution",
                "confession",
                "The Hidden Grudge",
                "Pressed by the complete chain of evidence, Julian admits he killed the professor before his own fraud could be exposed.",
                "Map room",
                [investigator, "Julian Pike"],
                ["E2", "E3", "E4", "E7", "E8", "E9"],
                ["The motive and method are fully confirmed."],
                "1:30 AM",
            ),
        ]

        return PlotPlan(case_title=case_bible.title, investigator=investigator, steps=steps)
